<a href="https://colab.research.google.com/github/RushiKawade/NumpyAndPandas/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
my_list = [1,2,3]

my_arr = np.array(my_list)

In [3]:
my_arr


array([1, 2, 3])

In [0]:
# similar to range function to create array in given lower and upper bound
arr2 = np.arange(1,10,2)

In [5]:
arr2

array([1, 3, 5, 7, 9])

In [6]:
#to create array of zeros
np.zeros(3)

array([0., 0., 0.])

In [7]:
#to create array of ones
np.ones(3)

array([1., 1., 1.])

In [8]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [9]:
# to create n linearly separated points between lowerbound and upperbound
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [10]:
# identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [11]:
np.random.rand(5)

array([0.83968924, 0.88123468, 0.65730173, 0.86589803, 0.43346404])

In [13]:
np.random.randint(0,100,10)

array([79, 60, 46, 14, 96, 92, 55, 29, 50, 56])

In [14]:
arr2.argmax()

4

In [15]:
arr2.shape

(5,)

In [0]:
arr = np.arange(10)

In [18]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
arr = arr.reshape(2,5)

In [20]:
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [25]:
#Numpy Indexing and Selection
arr2 = np.arange(10)

arr2[1:5]


array([1, 2, 3, 4])

In [26]:
#upto index 6
arr2[:6]

array([0, 1, 2, 3, 4, 5])

In [28]:
arr2[5:]

array([5, 6, 7, 8, 9])

In [0]:
# array sliceing note that it uses array refrence if any changes in slice will reflect in main array use copy to avoid that
slice_arr = arr2[4:9]

In [0]:
slice_arr[:]=100

In [31]:
slice_arr

array([100, 100, 100, 100, 100])

In [32]:
arr2

array([  0,   1,   2,   3, 100, 100, 100, 100, 100,   9])

In [0]:
copy_arr = arr2.copy()

In [35]:
copy_arr

array([  0,   1,   2,   3, 100, 100, 100, 100, 100,   9])

In [0]:
copy_arr[5:] = 100

In [37]:
copy_arr

array([  0,   1,   2,   3, 100, 100, 100, 100, 100, 100])

In [0]:
nd_arr = np.array([[1,4,6],[2,5,9],[3,6,7]]) 

In [39]:
nd_arr

array([[1, 4, 6],
       [2, 5, 9],
       [3, 6, 7]])

In [40]:
nd_arr[2][1]
nd_arr[2,1]

6

In [44]:
# select upto 2nd row and from 2nd column(excluding 1st column)
nd_arr[0:2,1:3]

array([[4, 6],
       [5, 9]])